apiVersion: v1
kind: PersistentVolume           
metadata:
  name: mysql-p-v
  labels:
    type: local
spec:
  storageClassName: standard       
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:                       
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain  
type: post
---    
apiVersion: v1
kind: PersistentVolumeClaim        
metadata:                          
  name: mysql-pv-c
  labels:
    app: polling-app
spec:                              
  storageClassName: standard      
  accessModes:
    - ReadWriteOnce               
  resources:
    requests:
      storage: 250Mi
type: post
---
apiVersion: v1                    
kind: Service                     
metadata:
  name: polling-app-mysql         
  labels:                        
    app: polling-app
spec:
  ports:
    - port: 3306
  selector:                      
    app: polling-app
    tier: mysql
  clusterIP: None
type: post
---
apiVersion: apps/v1
kind: Deployment                   
metadata:
  name: polling-app-mysql           
  labels:                          
    app: polling-app
spec:
  selector:
    matchLabels:                   
      app: polling-app
      tier: mysql
  strategy:
    type: Recreate
  template:                        
    metadata:
      labels:                       
        app: polling-app
        tier: mysql
    spec:                           
      containers:
      - image: mysql:5.7      
        name: mysql
        env:                        
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:                
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        ports:
        - containerPort: 3306               
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage  
          mountPath: /var/lib/mysql
      volumes:                      
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-c